version = 1

[[annotations]]
path = [
    ".eslintignore",
    ".github/**/",
    ".gitignore",
    ".prettierignore",
    ".prettierrc.json",
    "CHANGELOG.md",
    "README.md",
    "components.json",
    "eslint.config.js",
    "flake.lock",
    "flake.nix",
    "lib/**/",
    "middleware.ts",
    "next.config.js",
    "package-lock.json",
    "package.json",
    "postcss.config.js",
    "scripts/**/",
    "tailwind.config.ts",
    "tsconfig.json",
    "vitest.config.ts",
    "__fixtures__/**/",
    "__tests__/**/",
    "public/**/",
    "app/**/",
    "components/**/",
    "REUSE.toml"
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source LLC"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
