import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import "@rainbow-me/rainbowkit/styles.css";

const dmsans = DM_Sans({ subsets: ["latin"], weight: "200" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <Providers>
          <div className={`flex flex-col min-h-screen`}>
            <div className="sticky w-full flex justify-end pr-2 py-2 border-b">
              <ConnectButton />
            </div>
            <div className="flex flex-col flex-grow items-center justify-center">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
